---

name: Workflow Information
description: >
  Output information about the selected workflow and runs.
inputs:
  name:
    description: workflow name
    required: true
  branch:
    description: branch name, use "*" for all branches
    required: true
  repository:
    description: repository name (owner/repo)
    required: true
  token:
    description: token to use for API requests
    required: true
  conclusion:
    description: >
      Output information with workflows filtered by the specified conclusion,
      one of: action_required, cancelled, failure, neutral, success, skipped,
      stale, or timed_out.
  status:
    description: >
      Output information with workflows filtered by status,
      one of: queued, in_progress, or completed.
  job-name:
    description: >
      If specified, return the "running-jobs-count" of that job in the
      selected workflow runs.
outputs:
  running-workflows-count:
    description: >
      The number of selected workflow runs that are running.
  running-jobs-count:
    description: >
      The number of jobs that are running (status != completed) on the selected
      workflow runs, filtered by job-name. 0 if job-name not specified.
  last-build-run-number:
    description: >
      The run number of the last build of the selected workflow runs.
      This includes completed runs.
  last-build-sha:
    description: >
      The commit SHA of the last build of the selected workflow runs.
      This includes completed runs.
  workflow-id:
    description: The id of the specifed workflow.
runs:
  using: docker
  image: Dockerfile
  args:
    - --name
    - ${{ inputs.name }}
    - --branch
    - ${{ inputs.branch }}
    - --repository
    - ${{ inputs.repository }}
    - --token
    - ${{ inputs.token }}
    - --conclusion
    - ${{ inputs.conclusion }}
    - --status
    - ${{ inputs.status }}
    - --job-name
    - ${{ inputs.job-name }}
